# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

manhattan_neighborhoods = Neighborhood.create([
{borough: "Manhattan", name: "Battery Park City"},
{borough: "Manhattan", name: "Carnegie Hill"},
{borough: "Manhattan", name: "Chelsea"},
{borough: "Manhattan", name: "East Harlem"},
{borough: "Manhattan", name: "East Village"},
{borough: "Manhattan", name: "Financial District"},
{borough: "Manhattan", name: "Flatiron"},
{borough: "Manhattan", name: "Gramercy"},
{borough: "Manhattan", name: "Hamilton Heights"},
{borough: "Manhattan", name: "Harlem"},
{borough: "Manhattan", name: "Hudson Heights"},
{borough: "Manhattan", name: "Inwood"},
{borough: "Manhattan", name: "Kips Bay"},
{borough: "Manhattan", name: "Lower East Side"},
{borough: "Manhattan", name: "Manhattan Valley"},
{borough: "Manhattan", name: "Midtown East"},
{borough: "Manhattan", name: "Midtown West"},
{borough: "Manhattan", name: "Morningside Heights"},
{borough: "Manhattan", name: "Mt. Morris Park"},
{borough: "Manhattan", name: "Murray Hill"},
{borough: "Manhattan", name: "NoHo"},
{borough: "Manhattan", name: "Roosevelt Island"},
{borough: "Manhattan", name: "Seaport"},
{borough: "Manhattan", name: "Soho"},
{borough: "Manhattan", name: "Sugar Hill"},
{borough: "Manhattan", name: "Tribeca"},
{borough: "Manhattan", name: "Union Square"},
{borough: "Manhattan", name: "Upper East Side"},
{borough: "Manhattan", name: "Upper West Side"},
{borough: "Manhattan", name: "Village"},
{borough: "Manhattan", name: "Washington Heights"},
{borough: "Manhattan", name: "West Village"}])

queens_neighborhoods = Neighborhood.create([
{borough: "Queens", name: "Arverne"},
{borough: "Queens", name: "Astoria"},
{borough: "Queens", name: "Bayside"},
{borough: "Queens", name: "Beechhurst"},
{borough: "Queens", name: "Bellerose"},
{borough: "Queens", name: "Breezy Point"},
{borough: "Queens", name: "Briarwood"},
{borough: "Queens", name: "Broad Channel"},
{borough: "Queens", name: "Cambria Heights"},
{borough: "Queens", name: "College Point"},
{borough: "Queens", name: "Corona"},
{borough: "Queens", name: "Douglaston"},
{borough: "Queens", name: "East Elmhurst"},
{borough: "Queens", name: "Elmhurst"},
{borough: "Queens", name: "Far Rockaway"},
{borough: "Queens", name: "Floral Park"},
{borough: "Queens", name: "Flushing"},
{borough: "Queens", name: "Forest Hills"},
{borough: "Queens", name: "Fresh Meadows"},
{borough: "Queens", name: "Glen Oaks"},
{borough: "Queens", name: "Glendale"},
{borough: "Queens", name: "Hollis"},
{borough: "Queens", name: "Howard Beach"},
{borough: "Queens", name: "Jackson Heights"},
{borough: "Queens", name: "Jamaica"},
{borough: "Queens", name: "JFK Airport"},
{borough: "Queens", name: "Kew Gardens"},
{borough: "Queens", name: "Kew Gardens Hills"},
{borough: "Queens", name: "Little Neck"},
{borough: "Queens", name: "Long Island City"},
{borough: "Queens", name: "Maspeth"},
{borough: "Queens", name: "Middle Village"},
{borough: "Queens", name: "Ozone Park"},
{borough: "Queens", name: "Queens Village"},
{borough: "Queens", name: "Rego Park"},
{borough: "Queens", name: "Richmond Hill"},
{borough: "Queens", name: "Ridgewood"},
{borough: "Queens", name: "Rockaway Park"},
{borough: "Queens", name: "Rosedale"},
{borough: "Queens", name: "South Jamaica"},
{borough: "Queens", name: "South Ozone Park"},
{borough: "Queens", name: "Springfield Gardens"},
{borough: "Queens", name: "St. Albans"},
{borough: "Queens", name: "Sunnyside"},
{borough: "Queens", name: "Utopia"},
{borough: "Queens", name: "Whitestone"},
{borough: "Queens", name: "Woodhaven"},
{borough: "Queens", name: "Woodside"}])

# neighborhoods = Neighborhood.create([
#     {name: 'Lower Manhattan'}, 
#     {name: 'Tribeca'}, 
#     {name: 'Soho'}, 
#     {name: 'Greenwich Village'}, 
#     {name: 'East Village'}, 
#     {name: 'Lower East Side'}, 
#     {name: 'Nolita and Noho'}, 
#     {name: 'Gramercy Park and Murray Hill'}, 
#     {name: 'Chelsea'}, 
#     {name: 'Midtown East'}, 
#     {name: 'Midtown West and Hells Kitchen'}, 
#     {name: 'Upper East Side'}, 
#     {name: 'Upper West Side'}, 
#     {name: 'Morningside Heights'}, 
#     {name: 'Harlem'}, 
#     {name: 'Hamilton Heights and Washington Heights'}, 
#     {name: 'Brooklyn Heights and Cobble Hill'}, 
#     {name: 'Boerum Hill and Carroll Gardens'}, 
#     {name: 'Red Hook'}, 
#     {name: 'Dumbo'}, 
#     {name: 'Fort Greene and Clinton Hill'}, 
#     {name: 'Park Slope'}, 
#     {name: 'Beyond the Slope'}, 
#     {name: 'Williamsburg and Greenpoint'}, 
#     {name: 'Astoria and Long Island City'}
#     ])

